apiVersion: apps/v1
kind: Deployment
metadata:
  name: filesrepodb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: filesrepodb
  template:
    metadata:
      labels:
        app: filesrepodb
    spec:
      containers:
        - name: db
          image: mongo
          env:
            - name: MONGO_INITDB_DATABASE
              value: users
            - name: MONGO_INITDB_ROOT_USERNAME
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: username
            - name: MONGO_INITDB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: password
          ports:
            - containerPort: 27017
          volumeMounts:
            - name: mongo-persistent-storage
              mountPath: /data/db
      volumes:
        - name: mongo-persistent-storage
          persistentVolumeClaim:
            claimName: mongo-pv-claim

---
#service
apiVersion: v1
kind: Service
metadata:
  name: mongodb-service
spec:
  selector:
    app: filesrepodb
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017
  type: ClusterIP

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-express-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo-express
  template:
    metadata:
      labels:
        app: mongo-express
    spec:
      containers:
        - name: mongo-express
          image: mongo-express
          env:
            - name: ME_CONFIG_MONGODB_SERVER
              value: mongodb-service
            - name: ME_CONFIG_MONGODB_PORT
              value: "27017"   # Add double quotes around the value
            - name: ME_CONFIG_MONGODB_ADMINUSERNAME
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: username
            - name: ME_CONFIG_MONGODB_ADMINPASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: password
          ports:
            - containerPort: 8081
---
apiVersion: v1
kind: Service
metadata:
  name: mongo-express-service
spec:
  selector:
    app: mongo-express
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
  type: LoadBalancer
